### ISSUE TITLE
an error and some features

### ISSUE THREAD

**Issue by srzern** [febryardiansyah/mangamint-website#1]
Hi,
I get this error commonly `Oh snap! Data won't loaded!
Please refresh your browser`  but when f5 the page its get load.

A comment system like disqus  will be good in manga  and chapter page.
A login, register for bookmark mangas, last readed chapter etc.( you can use strapi maybe for this)
A chapter search box for manga which has a  lot of chapters

**Comment by febryardiansyah** [comment]
Hello, thanks for opening an issue. But you know, actually this project was proposed to complete my college assignment. I don't know i'll add some features that you were requested.

And for the error, it comes from the API. I'll check it later

Thanks

**Comment by srzern** [comment]
ah, okay 🤦‍♂️ good luck with 😄
